### ISSUE TITLE
Likelihood calculation errors

### ISSUE THREAD

**Issue by max-hill** [rabier/MySnappNet#2]
Running BEAST v2.6.6 on Debian 10 with the example data `SnappNet/example/JDD1.xml ` yields likelihood calculation errors.

Example: Running the command

`./beast -overwrite -threads -1 ../../../SnappNet/example/JDD1.xml > output.txt`

the following is printed to terminal:

```
Setting number of threads to 12
File: JDD1.xml seed: 1645903370389 threads: 12
Loading package BEAST v2.6.6
Loading package SnappNet v1.0.0
Loading package BEAST v2.6.6
Or3: 5682 3
Jap: 5682 3
Aus: 5682 3
Ind: 5682 3
Aro: 5682 3
Or1: 5682 3
Warning: Overwriting file test_3s.xml.trace.log
Warning: Overwriting file test_3s.xml.species.trees
At sample 10000
Likelihood incorrectly calculated: -38128.36895371382 != -38783.21060753704(654.8416538232195) Operator: snappNetProject.operators.ChangeAllGamma(ChangeAllGamma)
```
and then similar "likelihood incorrectly calculated" errors are printed every 10000 samples. This occurs also if i set the number of threads to one.

Also, we had to pipe standard output to the file `output.txt` otherwise we get a deluge of output lines  of the form

```
Je suis le pattern 307

Voici ma valeur de freq 0.0

Je suis le pattern 308

Voici ma valeur de freq 6318.0

Ds SNapNetPrior, voici log P-193.06296831605727

```
Is there a way to silence this output, other than by simply piping output to a file?

**Comment by rabier** [comment]
Hello,
I think you are not using the good files. You  should have a look in the doc folder. 
The right command line is 
java -jar SnappNetProjectToRun.jar JDD1.xml > MyOutput

Best
CE Rabier

ps: A message should always start with "hello" and end with "thanks for your help".

**Comment by max-hill** [comment]
Okay thank you! We were able to get it working. Appreciate your help!
